---

- hosts: app
  vars:
    http_port: 80
  remote_user: root
  tasks:
  - name:  apache install
    apt: pkg=apache2 state=present
    notify:
    - restart apache
  - name: apace runn ensure
    service: name=apache2 state=started
  handlers:
  - name: restart apache
    service: name=apache2 state=restarted
