---

- hosts: all
  vars:
    http_port: 80
  remote_user: jboss
  tasks:
  - name:  apache restart
    service: name=apache2 state=restarted
    notify:
    - restart apache
  handlers:
  - name: restart apache
    service: name=apache2 state=restarted
